version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql_gestion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mouad@2004
      MYSQL_DATABASE: gestionstock
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmouad@2004"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  backend:
    build: ./backend
    container_name: gestion_backend
    restart: on-failure:5
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestionstock
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mouad@2004
    ports:
      - "8080:8080"

volumes:
  mysql_data: