spring.application.name=backend
# Port du serveur
server.port=8082

# Configuration H2 (pour développement)
spring.datasource.url=jdbc:mysql://localhost:3306/gestionStock
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mouad@2004

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect