# ===================================================
# APPLICATION
# ===================================================
spring.application.name=backend
# port de l'equipe 
server.port=8080

# ===================================================
# BASE DE DONN\u00c9ES MySQL
# ===================================================
spring.datasource.url=jdbc:mysql://localhost:3306/gestionstock
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# ===================================================
# JPA / HIBERNATE
# ===================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Utiliser MySQL8Dialect si MySQL 8 est install\u00e9, sinon MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===================================================
# LOGGING POUR DEBUG (UTILISABLE POUR GESTION FOURNISSEURS)
# ===================================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.java.gestion_stock=DEBUG


# JWT
security.jwt.secret=R0c0y5VmMFRtTXI0V1p4ckR5Ym9pTE94Q2tCdlB6SkJ5Wk5jSWd1MldyTHc1ZzI4